-- Pirganj – আপনার এলাকার তথ্যসেবা
-- Run once in Supabase SQL Editor.
-- This creates the application tables only. Keep Supabase service_role keys server-side.

create extension if not exists pgcrypto;

create type public.user_role as enum ('user', 'admin');
create type public.service_status as enum ('pending', 'published', 'rejected');
create type public.content_status as enum ('published', 'hidden', 'removed');
create type public.comment_status as enum ('visible', 'hidden', 'removed');
create type public.review_status as enum ('visible', 'hidden', 'removed');
create type public.urgency as enum ('normal', 'urgent', 'critical');
create type public.emergency_status as enum ('open', 'closed');
create type public.report_status as enum ('open', 'dismissed', 'resolved');
create type public.recovery_status as enum ('pending', 'approved', 'rejected', 'completed');
create type public.version_status as enum ('draft', 'published', 'archived');

create table public.users (
  id integer generated by default as identity primary key,
  open_id varchar(128) not null unique,
  username varchar(64),
  phone varchar(24),
  name text,
  email varchar(320),
  age integer check (age is null or age between 1 and 120),
  profile_image_url varchar(512),
  login_method varchar(64),
  role public.user_role not null default 'user',
  is_posting_restricted boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_signed_in timestamptz not null default now()
);
create unique index users_username_ci_unique on public.users (lower(username)) where username is not null;
create unique index users_phone_unique on public.users (phone) where phone is not null;
create index users_phone_idx on public.users (phone);

create table public.categories (
  id integer generated by default as identity primary key,
  name varchar(120) not null,
  slug varchar(120) not null unique,
  icon varchar(80),
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.services (
  id integer generated by default as identity primary key,
  category_id integer references public.categories(id) on delete set null,
  submitted_by integer references public.users(id) on delete set null,
  name varchar(180) not null,
  short_description varchar(500),
  description text,
  phone varchar(24),
  address varchar(300),
  opening_hours varchar(300),
  map_url varchar(1000),
  image_url varchar(1000),
  average_rating numeric(3,2) not null default 0.00 check (average_rating between 0 and 5),
  review_count integer not null default 0,
  status public.service_status not null default 'published',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index services_category_idx on public.services(category_id);
create index services_status_idx on public.services(status);

create table public.posts (
  id integer generated by default as identity primary key,
  author_id integer references public.users(id) on delete set null,
  category varchar(80) not null default 'সাধারণ',
  title varchar(180),
  content text,
  image_urls text,
  location varchar(300),
  contact varchar(80),
  lost_found_type varchar(80),
  is_pinned boolean not null default false,
  status public.content_status not null default 'published',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index posts_feed_idx on public.posts(is_pinned desc, created_at desc);
create index posts_category_idx on public.posts(category);

create table public.comments (
  id integer generated by default as identity primary key,
  post_id integer not null references public.posts(id) on delete cascade,
  author_id integer not null references public.users(id) on delete cascade,
  parent_id integer references public.comments(id) on delete cascade,
  body varchar(1000) not null,
  status public.comment_status not null default 'visible',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index comments_post_idx on public.comments(post_id);

create table public.reactions (
  id integer generated by default as identity primary key,
  post_id integer not null references public.posts(id) on delete cascade,
  user_id integer not null references public.users(id) on delete cascade,
  type varchar(30) not null default 'like',
  created_at timestamptz not null default now(),
  unique(post_id, user_id)
);

create table public.reviews (
  id integer generated by default as identity primary key,
  service_id integer not null references public.services(id) on delete cascade,
  user_id integer not null references public.users(id) on delete cascade,
  rating integer not null check (rating between 1 and 5),
  body varchar(1000),
  status public.review_status not null default 'visible',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(service_id, user_id)
);
create index reviews_service_idx on public.reviews(service_id);

create table public.blood_donors (
  id integer generated by default as identity primary key,
  user_id integer not null references public.users(id) on delete cascade unique,
  name varchar(160) not null,
  blood_group varchar(5) not null,
  area varchar(120) not null,
  phone varchar(24) not null,
  is_available boolean not null default true,
  note varchar(500),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index blood_donors_group_area_idx on public.blood_donors(blood_group, area);

create table public.emergency_requests (
  id integer generated by default as identity primary key,
  author_id integer references public.users(id) on delete set null,
  type varchar(80) not null,
  blood_group varchar(5),
  required_amount varchar(40),
  hospital varchar(240),
  location varchar(300),
  contact varchar(80) not null,
  urgency public.urgency not null default 'urgent',
  message text,
  status public.emergency_status not null default 'open',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index emergency_blood_idx on public.emergency_requests(blood_group, status);

create table public.notification_tokens (
  id integer generated by default as identity primary key,
  user_id integer not null references public.users(id) on delete cascade,
  token varchar(512) not null unique,
  platform varchar(30) not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index notification_tokens_user_idx on public.notification_tokens(user_id);

create table public.notifications (
  id integer generated by default as identity primary key,
  user_id integer references public.users(id) on delete cascade,
  title varchar(180) not null,
  message varchar(1000) not null,
  deep_link varchar(500),
  target_type varchar(40) not null default 'system',
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);
create index notifications_user_idx on public.notifications(user_id, created_at desc);

create table public.reports (
  id integer generated by default as identity primary key,
  reporter_id integer references public.users(id) on delete set null,
  target_type varchar(40) not null,
  target_id integer not null,
  reason varchar(120) not null,
  note varchar(500),
  status public.report_status not null default 'open',
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);
create index reports_status_idx on public.reports(status, created_at desc);

create table public.password_recovery_requests (
  id integer generated by default as identity primary key,
  phone varchar(24) not null,
  note varchar(500),
  status public.recovery_status not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.app_versions (
  id integer generated by default as identity primary key,
  version_name varchar(40) not null,
  version_code integer not null,
  apk_url varchar(1000) not null,
  release_notes text,
  minimum_version_code integer not null,
  force_update boolean not null default false,
  release_date timestamptz not null default now(),
  apk_size varchar(40),
  status public.version_status not null default 'published',
  created_at timestamptz not null default now()
);
create index app_versions_code_idx on public.app_versions(version_code desc, status);

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger users_set_updated_at before update on public.users for each row execute function public.set_updated_at();
create trigger categories_set_updated_at before update on public.categories for each row execute function public.set_updated_at();
create trigger services_set_updated_at before update on public.services for each row execute function public.set_updated_at();
create trigger posts_set_updated_at before update on public.posts for each row execute function public.set_updated_at();
create trigger comments_set_updated_at before update on public.comments for each row execute function public.set_updated_at();
create trigger reviews_set_updated_at before update on public.reviews for each row execute function public.set_updated_at();
create trigger blood_donors_set_updated_at before update on public.blood_donors for each row execute function public.set_updated_at();
create trigger emergency_requests_set_updated_at before update on public.emergency_requests for each row execute function public.set_updated_at();
create trigger notification_tokens_set_updated_at before update on public.notification_tokens for each row execute function public.set_updated_at();
create trigger password_recovery_requests_set_updated_at before update on public.password_recovery_requests for each row execute function public.set_updated_at();

-- Seed categories only; no personal user data is inserted.
insert into public.categories (name, slug, icon, sort_order) values
  ('হাসপাতাল', 'hospital', 'hospital', 1),
  ('ডাক্তার', 'doctor', 'stethoscope', 2),
  ('ফার্মেসি', 'pharmacy', 'pill', 3),
  ('অ্যাম্বুলেন্স', 'ambulance', 'ambulance', 4),
  ('স্কুল', 'school', 'school', 5),
  ('কলেজ', 'college', 'graduation-cap', 6),
  ('সরকারি অফিস', 'government-office', 'building', 7),
  ('রেস্টুরেন্ট', 'restaurant', 'utensils', 8),
  ('দোকান', 'shop', 'store', 9),
  ('অন্যান্য স্থানীয় সেবা', 'other', 'grid', 10)
on conflict (slug) do nothing;

-- Optional first version record. Replace the APK URL before production release.
-- insert into public.app_versions (version_name, version_code, apk_url, minimum_version_code, release_notes, force_update)
-- values ('1.0.0', 1, 'https://pirganj-apk-release.netlify.app/', 1, 'প্রথম সংস্করণ', false);
